# ======================================================
# JUPYTER BOOK CONFIGURATION — FORMAR INNOVAR
# ======================================================

title: "Formar Innovar · Educational Analytics Project"
author: "Data Analytics Team"
logo: images/FICC.png  # Logo de FICC
copyright: "© 2025 Formar Innovar"

only_build_toc_files: true
execute:
  execute_notebooks: "off" # No ejecutar código (solo Markdown)

html:
  favicon: images/favicon.ico
  use_repository_button: false
  use_edit_page_button: false
  use_issues_button: false
  home_page_in_navbar: true
  extra_navbar: |
    <div style="font-size:0.85rem; color:gray;">
    Proyecto de analítica educativa del Colegio Formar Innovar<br>
    <a href="https://jupyterbook.org" target="_blank">Built with Jupyter Book</a>
    </div>

sphinx:
  config:
    language: es
    html_static_path: ["images"]
    # Configuración para manejar caracteres especiales
    source_suffix: ['.md', '.rst']
    source_encoding: 'utf-8'
    master_doc: 'index'
    # Configuración de imágenes
    html_copy_source: false
    html_show_sourcelink: false
    # Configuración de codificación
    default_role: 'any'
    html_theme_options:
      navigation_depth: 3
      use_repository_button: false
      use_edit_page_button: false
      use_issues_button: false

exclude_patterns:
  - "_build"
  - "Thumbs.db"
  - ".DS_Store"

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - substitution
  myst_url_schemes: ["http", "https", "mailto"]
  myst_heading_anchors: 3
